using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Notes;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Notes;
internal sealed class NoteService(ApplicationDbContext db):INoteService
{
 public async Task<IReadOnlyList<StudentNoteDto>>GetAsync(string s,CancellationToken ct=default)=>await db.StudentNotes.AsNoTracking().Where(x=>x.StudentUserId==s).OrderByDescending(x=>x.UpdatedAtUtc).Select(x=>new StudentNoteDto(x.Id,x.CourseId,x.Course==null?null:x.Course.CourseCode,x.Title,x.Content,x.UpdatedAtUtc)).ToListAsync(ct);
 public async Task<IReadOnlyList<NoteCourseDto>>GetCoursesAsync(string s,CancellationToken ct=default)=>await db.CourseEnrollments.AsNoTracking().Where(x=>x.StudentUserId==s&&x.Status==EnrollmentStatus.Approved).Select(x=>new NoteCourseDto(x.CourseId,x.Course.CourseCode,x.Course.Name)).ToListAsync(ct);
 public async Task<NoteActionResult>CreateAsync(string s,int? c,string t,string content,CancellationToken ct=default){if(!Valid(t,content))return NoteActionResult.Invalid;if(!await ValidCourse(s,c,ct))return NoteActionResult.Forbidden;db.Add(new StudentNote{StudentUserId=s,CourseId=c,Title=t.Trim(),Content=content.Trim()});await db.SaveChangesAsync(ct);return NoteActionResult.Success;}
 public async Task<NoteActionResult>UpdateAsync(string s,int id,int? c,string t,string content,CancellationToken ct=default){if(!Valid(t,content))return NoteActionResult.Invalid;var x=await db.StudentNotes.FirstOrDefaultAsync(x=>x.Id==id&&x.StudentUserId==s,ct);if(x is null)return NoteActionResult.NotFound;if(!await ValidCourse(s,c,ct))return NoteActionResult.Forbidden;x.CourseId=c;x.Title=t.Trim();x.Content=content.Trim();x.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync(ct);return NoteActionResult.Success;}
 public async Task<NoteActionResult>DeleteAsync(string s,int id,CancellationToken ct=default){var x=await db.StudentNotes.FirstOrDefaultAsync(x=>x.Id==id&&x.StudentUserId==s,ct);if(x is null)return NoteActionResult.NotFound;db.Remove(x);await db.SaveChangesAsync(ct);return NoteActionResult.Success;}
 private Task<bool>ValidCourse(string s,int?c,CancellationToken ct)=>c is null?Task.FromResult(true):db.CourseEnrollments.AnyAsync(x=>x.StudentUserId==s&&x.CourseId==c&&x.Status==EnrollmentStatus.Approved,ct);private static bool Valid(string t,string c)=>!string.IsNullOrWhiteSpace(t)&&!string.IsNullOrWhiteSpace(c)&&t.Trim().Length<=200&&c.Trim().Length<=8000;
}
