using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.Rendering;using TechnifyERP.Application.Admin;using TechnifyERP.Application.Courses;using TechnifyERP.Application.Notices;using TechnifyERP.Domain.Enums;
namespace TechnifyERP.Areas.Admin.Controllers;
[Area("Admin"),Authorize(Roles="SuperAdmin")]
public sealed class NoticesController(INoticeService notices,ICourseService courses,IAdminDirectoryService directory,IWebHostEnvironment env):Controller
{
 public async Task<IActionResult>Index(CancellationToken ct){ViewBag.Notices=await notices.GetCreatedAsync(UserId,ct);ViewBag.Courses=(await courses.GetAllAsync(ct)).Select(x=>new SelectListItem($"{x.CourseCode} — {x.Name}",x.Id.ToString()));ViewBag.Students=(await directory.GetStudentsAsync(ct)).Select(x=>new SelectListItem($"{x.RegistrationNumber} — {x.FullName}",x.UserId));return View();}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Create(string title,string message,NoticeAudience audience,int? courseId,string? studentUserId,IFormFile? image,CancellationToken ct){var path=await SaveImage(image,ct);if(image is not null&&path is null){TempData["ErrorMessage"]="Image JPG/PNG/WEBP aur max 5 MB honi chahiye.";return RedirectToAction(nameof(Index));}var r=await notices.CreateAdminAsync(UserId,new(title,message,audience,courseId,studentUserId,path),ct);TempData[r==NoticeActionResult.Success?"SuccessMessage":"ErrorMessage"]=r==NoticeActionResult.Success?"Notice publish ho gaya.":"Audience aur fields check karein.";return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Delete(int id,CancellationToken ct){await notices.DeleteAsync(UserId,id,ct);return RedirectToAction(nameof(Index));}
 private async Task<string?>SaveImage(IFormFile?f,CancellationToken ct){if(f is null)return null;if(f.Length<=0||f.Length>5*1024*1024)return null;var ext=Path.GetExtension(f.FileName);if(!new[]{".jpg",".jpeg",".png",".webp"}.Contains(ext,StringComparer.OrdinalIgnoreCase))return null;var folder=Path.Combine(env.WebRootPath,"uploads","notices");Directory.CreateDirectory(folder);var name=$"{Guid.NewGuid():N}{ext.ToLowerInvariant()}";await using var stream=System.IO.File.Create(Path.Combine(folder,name));await f.CopyToAsync(stream,ct);return $"/uploads/notices/{name}";}
 private string UserId=>User.FindFirstValue(ClaimTypes.NameIdentifier)??throw new InvalidOperationException();
}
