using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Schedules;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Schedules;
internal sealed class ScheduleService(ApplicationDbContext db):IScheduleService
{
 public async Task<IReadOnlyList<FacultyCourseOptionDto>>GetOptionsAsync(CancellationToken ct=default)=>await(from x in db.FacultyCourses.AsNoTracking() join u in db.Users.AsNoTracking() on x.FacultyUserId equals u.Id orderby x.Course.CourseCode,u.FullName select new FacultyCourseOptionDto(u.Id,u.FullName,x.CourseId,x.Course.CourseCode,x.Course.Name)).ToListAsync(ct);
 public async Task<IReadOnlyList<ClassScheduleDto>>GetAllAsync(CancellationToken ct=default)=>await Project(db.ClassSchedules.AsNoTracking().OrderBy(x=>x.DayOfWeek).ThenBy(x=>x.StartTime)).ToListAsync(ct);
 public async Task<ScheduleActionResult>CreateAsync(SaveScheduleRequest r,CancellationToken ct=default){if(r.CourseId<1||string.IsNullOrWhiteSpace(r.FacultyUserId)||string.IsNullOrWhiteSpace(r.Room)||r.StartTime>=r.EndTime)return ScheduleActionResult.Invalid;if(!await db.FacultyCourses.AnyAsync(x=>x.FacultyUserId==r.FacultyUserId&&x.CourseId==r.CourseId,ct))return ScheduleActionResult.FacultyNotAssigned;var conflict=await db.ClassSchedules.AnyAsync(x=>x.DayOfWeek==r.DayOfWeek&&x.StartTime<r.EndTime&&x.EndTime>r.StartTime&&(x.FacultyUserId==r.FacultyUserId||x.Room==r.Room.Trim()),ct);if(conflict)return ScheduleActionResult.Conflict;db.Add(new ClassSchedule{CourseId=r.CourseId,FacultyUserId=r.FacultyUserId,DayOfWeek=r.DayOfWeek,StartTime=r.StartTime,EndTime=r.EndTime,Room=r.Room.Trim()});await db.SaveChangesAsync(ct);return ScheduleActionResult.Success;}
 public async Task<ScheduleActionResult>DeleteAsync(int id,CancellationToken ct=default){var x=await db.ClassSchedules.FindAsync([id],ct);if(x is null)return ScheduleActionResult.NotFound;db.Remove(x);await db.SaveChangesAsync(ct);return ScheduleActionResult.Success;}
 public async Task<IReadOnlyList<ClassScheduleDto>>GetFacultyScheduleAsync(string f,CancellationToken ct=default)=>await Project(db.ClassSchedules.AsNoTracking().Where(x=>x.FacultyUserId==f).OrderBy(x=>x.DayOfWeek).ThenBy(x=>x.StartTime)).ToListAsync(ct);
 public async Task<IReadOnlyList<ClassScheduleDto>>GetStudentScheduleAsync(string s,CancellationToken ct=default){var courses=db.CourseEnrollments.Where(x=>x.StudentUserId==s&&x.Status==EnrollmentStatus.Approved).Select(x=>x.CourseId);return await Project(db.ClassSchedules.AsNoTracking().Where(x=>courses.Contains(x.CourseId)).OrderBy(x=>x.DayOfWeek).ThenBy(x=>x.StartTime)).ToListAsync(ct);}
 private IQueryable<ClassScheduleDto>Project(IQueryable<ClassSchedule>q)=>from x in q join u in db.Users.AsNoTracking() on x.FacultyUserId equals u.Id select new ClassScheduleDto(x.Id,x.CourseId,x.Course.CourseCode,x.Course.Name,u.Id,u.FullName,x.DayOfWeek,x.StartTime,x.EndTime,x.Room);
}
