using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Doubts;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Doubts;
internal sealed class DoubtService(ApplicationDbContext db):IDoubtService
{
 public async Task<IReadOnlyList<DoubtCourseDto>>GetStudentCoursesAsync(string s,CancellationToken ct=default)=>await db.CourseEnrollments.AsNoTracking().Where(x=>x.StudentUserId==s&&x.Status==EnrollmentStatus.Approved).OrderBy(x=>x.Course.CourseCode).Select(x=>new DoubtCourseDto(x.CourseId,x.Course.CourseCode,x.Course.Name)).ToListAsync(ct);
 public async Task<IReadOnlyList<DoubtDto>>GetStudentDoubtsAsync(string s,CancellationToken ct=default)=>await Project(db.StudentDoubts.AsNoTracking().Where(x=>x.StudentUserId==s).OrderByDescending(x=>x.AskedAtUtc)).ToListAsync(ct);
 public async Task<DoubtActionResult>AskAsync(string s,int c,string q,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(q))return DoubtActionResult.Invalid;if(!await db.CourseEnrollments.AnyAsync(x=>x.StudentUserId==s&&x.CourseId==c&&x.Status==EnrollmentStatus.Approved,ct))return DoubtActionResult.Forbidden;db.Add(new StudentDoubt{StudentUserId=s,CourseId=c,Question=q.Trim()});await db.SaveChangesAsync(ct);return DoubtActionResult.Success;}
 public async Task<IReadOnlyList<DoubtDto>>GetFacultyDoubtsAsync(string f,CancellationToken ct=default){var ids=db.FacultyCourses.Where(x=>x.FacultyUserId==f).Select(x=>x.CourseId);return await Project(db.StudentDoubts.AsNoTracking().Where(x=>ids.Contains(x.CourseId)).OrderBy(x=>x.Answer!=null).ThenByDescending(x=>x.AskedAtUtc)).ToListAsync(ct);}
 public async Task<IReadOnlyList<DoubtDto>>GetAllAsync(CancellationToken ct=default)=>await Project(db.StudentDoubts.AsNoTracking().OrderBy(x=>x.Answer!=null).ThenByDescending(x=>x.AskedAtUtc)).ToListAsync(ct);
 public async Task<DoubtActionResult>AnswerFacultyAsync(string f,int id,string a,CancellationToken ct=default){var x=await db.StudentDoubts.FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return DoubtActionResult.NotFound;if(!await db.FacultyCourses.AnyAsync(y=>y.FacultyUserId==f&&y.CourseId==x.CourseId,ct))return DoubtActionResult.Forbidden;return await Answer(x,f,a,ct);}
 public async Task<DoubtActionResult>AnswerAdminAsync(string admin,int id,string a,CancellationToken ct=default){var x=await db.StudentDoubts.FirstOrDefaultAsync(x=>x.Id==id,ct);return x is null?DoubtActionResult.NotFound:await Answer(x,admin,a,ct);}
 private async Task<DoubtActionResult>Answer(StudentDoubt x,string user,string a,CancellationToken ct){if(string.IsNullOrWhiteSpace(a))return DoubtActionResult.Invalid;x.Answer=a.Trim();x.AnsweredByUserId=user;x.AnsweredAtUtc=DateTime.UtcNow;await db.SaveChangesAsync(ct);return DoubtActionResult.Success;}
 private IQueryable<DoubtDto>Project(IQueryable<StudentDoubt>q)=>from x in q join student in db.Users.AsNoTracking() on x.StudentUserId equals student.Id join profile in db.StudentProfiles.AsNoTracking() on student.Id equals profile.UserId join answerer in db.Users.AsNoTracking() on x.AnsweredByUserId equals answerer.Id into answerers from answerer in answerers.DefaultIfEmpty() select new DoubtDto(x.Id,x.CourseId,x.Course.CourseCode,x.Course.Name,student.FullName,profile.RegistrationNumber,x.Question,x.AskedAtUtc,x.Answer,answerer==null?null:answerer.FullName,x.AnsweredAtUtc);
}
