using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Tests;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Tests;
internal sealed class TestService(ApplicationDbContext db):ITestService
{
 public async Task<IReadOnlyList<TestDto>> GetFacultyTestsAsync(string f,CancellationToken ct=default)=>await Project(db.CourseTests.AsNoTracking().Where(x=>x.FacultyUserId==f).OrderByDescending(x=>x.StartsAtUtc)).ToListAsync(ct);
 public async Task<(TestActionResult Result,int Id)> CreateAsync(string f,SaveTestRequest r,CancellationToken ct=default){if(r.CourseId<1||string.IsNullOrWhiteSpace(r.Title)||r.DurationMinutes<1||r.EndsAtUtc<=r.StartsAtUtc)return(TestActionResult.Invalid,0);if(!await db.FacultyCourses.AnyAsync(x=>x.FacultyUserId==f&&x.CourseId==r.CourseId,ct))return(TestActionResult.Forbidden,0);var x=new CourseTest{CourseId=r.CourseId,FacultyUserId=f,Title=r.Title.Trim(),DurationMinutes=r.DurationMinutes,StartsAtUtc=r.StartsAtUtc,EndsAtUtc=r.EndsAtUtc};db.Add(x);await db.SaveChangesAsync(ct);return(TestActionResult.Success,x.Id);}
 public async Task<TestDto?> GetFacultyTestAsync(string f,int id,CancellationToken ct=default)=>await Project(db.CourseTests.AsNoTracking().Where(x=>x.FacultyUserId==f&&x.Id==id)).FirstOrDefaultAsync(ct);
 public async Task<IReadOnlyList<QuestionDto>?> GetQuestionsAsync(string f,int id,CancellationToken ct=default){if(!await db.CourseTests.AnyAsync(x=>x.Id==id&&x.FacultyUserId==f,ct))return null;return await db.TestQuestions.AsNoTracking().Where(x=>x.TestId==id).Select(x=>new QuestionDto(x.Id,x.Text,x.OptionA,x.OptionB,x.OptionC,x.OptionD,x.CorrectOption,x.Marks)).ToListAsync(ct);}
 public async Task<TestActionResult> AddQuestionAsync(string f,int id,SaveQuestionRequest r,CancellationToken ct=default){var test=await db.CourseTests.FirstOrDefaultAsync(x=>x.Id==id&&x.FacultyUserId==f,ct);if(test is null)return TestActionResult.NotFound;var correct=char.ToUpperInvariant(r.CorrectOption);if(r.Marks<=0||!"ABCD".Contains(correct)||new[]{r.Text,r.OptionA,r.OptionB,r.OptionC,r.OptionD}.Any(string.IsNullOrWhiteSpace))return TestActionResult.Invalid;db.Add(new TestQuestion{TestId=id,Text=r.Text.Trim(),OptionA=r.OptionA.Trim(),OptionB=r.OptionB.Trim(),OptionC=r.OptionC.Trim(),OptionD=r.OptionD.Trim(),CorrectOption=correct,Marks=r.Marks});test.TotalMarks+=r.Marks;await db.SaveChangesAsync(ct);return TestActionResult.Success;}
 public async Task<TestActionResult> DeleteQuestionAsync(string f,int q,CancellationToken ct=default){var item=await db.TestQuestions.Include(x=>x.Test).FirstOrDefaultAsync(x=>x.Id==q&&x.Test.FacultyUserId==f,ct);if(item is null)return TestActionResult.NotFound;item.Test.TotalMarks-=item.Marks;db.Remove(item);await db.SaveChangesAsync(ct);return TestActionResult.Success;}
 public async Task<IReadOnlyList<StudentTestDto>> GetStudentTestsAsync(string s,CancellationToken ct=default)=>await(from t in db.CourseTests.AsNoTracking() join e in db.CourseEnrollments.AsNoTracking() on t.CourseId equals e.CourseId where e.StudentUserId==s&&e.Status==EnrollmentStatus.Approved let result=t.Results.FirstOrDefault(x=>x.StudentUserId==s) orderby t.StartsAtUtc descending select new StudentTestDto(t.Id,t.Course.CourseCode,t.Title,t.DurationMinutes,t.TotalMarks,t.StartsAtUtc,t.EndsAtUtc,result!=null,result==null?null:result.Score)).ToListAsync(ct);
 public async Task<TestAttemptDto?> GetAttemptAsync(string s,int id,CancellationToken ct=default){var now=DateTime.UtcNow;if(await db.TestResults.AnyAsync(x=>x.TestId==id&&x.StudentUserId==s,ct))return null;if(!await db.CourseEnrollments.AnyAsync(e=>e.StudentUserId==s&&e.Status==EnrollmentStatus.Approved&&e.Course.Tests.Any(t=>t.Id==id&&t.StartsAtUtc<=now&&t.EndsAtUtc>=now),ct))return null;return await db.CourseTests.AsNoTracking().Where(x=>x.Id==id).Select(x=>new TestAttemptDto(x.Id,x.Title,x.DurationMinutes,x.EndsAtUtc,x.Questions.Select(q=>new QuestionDto(q.Id,q.Text,q.OptionA,q.OptionB,q.OptionC,q.OptionD,' ',q.Marks)).ToList())).FirstOrDefaultAsync(ct);}
 public async Task<(TestActionResult Result,int ResultId)> SubmitAsync(string s,int id,IReadOnlyList<SubmittedAnswer> answers,CancellationToken ct=default){var now=DateTime.UtcNow;var test=await db.CourseTests.Include(x=>x.Questions).FirstOrDefaultAsync(x=>x.Id==id,ct);if(test is null)return(TestActionResult.NotFound,0);if(now<test.StartsAtUtc||now>test.EndsAtUtc)return(TestActionResult.NotActive,0);if(await db.TestResults.AnyAsync(x=>x.TestId==id&&x.StudentUserId==s,ct))return(TestActionResult.AlreadyAttempted,0);if(!await db.CourseEnrollments.AnyAsync(x=>x.StudentUserId==s&&x.CourseId==test.CourseId&&x.Status==EnrollmentStatus.Approved,ct))return(TestActionResult.Forbidden,0);var map=answers.GroupBy(x=>x.QuestionId).ToDictionary(x=>x.Key,x=>x.Last().SelectedOption);var result=new TestResult{TestId=id,StudentUserId=s,StartedAtUtc=now,SubmittedAtUtc=now};foreach(var q in test.Questions){map.TryGetValue(q.Id,out var selected);var correct=selected.HasValue&&char.ToUpperInvariant(selected.Value)==q.CorrectOption;result.Answers.Add(new TestAnswer{QuestionId=q.Id,SelectedOption=selected,IsCorrect=correct,MarksAwarded=correct?q.Marks:0});if(correct)result.Score+=q.Marks;}db.Add(result);await db.SaveChangesAsync(ct);return(TestActionResult.Success,result.Id);}
 public async Task<TestResultDto?> GetResultAsync(string s,int id,CancellationToken ct=default)=>await(from r in db.TestResults.AsNoTracking() join u in db.Users.AsNoTracking() on r.StudentUserId equals u.Id where r.Id==id&&r.StudentUserId==s select new TestResultDto(r.Test.Title,u.FullName,r.Score,r.Test.TotalMarks,r.Test.TotalMarks==0?0:r.Score*100/r.Test.TotalMarks,r.SubmittedAtUtc)).FirstOrDefaultAsync(ct);
 private static IQueryable<TestDto> Project(IQueryable<CourseTest> q)=>q.Select(x=>new TestDto(x.Id,x.CourseId,x.Course.CourseCode,x.Course.Name,x.Title,x.DurationMinutes,x.TotalMarks,x.StartsAtUtc,x.EndsAtUtc,x.Questions.Count,x.Results.Count));
}
