using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Certificates;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Certificates;
internal sealed class CertificateService(ApplicationDbContext db):ICertificateService
{
 public async Task<IReadOnlyList<EligibleCertificateStudentDto>>GetEligibleAsync(CancellationToken ct=default)=>await(from e in db.CourseEnrollments.AsNoTracking() join u in db.Users.AsNoTracking() on e.StudentUserId equals u.Id join p in db.StudentProfiles.AsNoTracking() on u.Id equals p.UserId where e.Status==EnrollmentStatus.Approved orderby u.FullName select new EligibleCertificateStudentDto(u.Id,u.FullName,p.RegistrationNumber,e.CourseId,e.Course.CourseCode,e.Course.Name)).ToListAsync(ct);
 public async Task<IReadOnlyList<CertificateDto>>GetAllAsync(CancellationToken ct=default)=>await Project(db.CourseCertificates.AsNoTracking().OrderByDescending(x=>x.IssueDate)).ToListAsync(ct);
 public async Task<(CertificateActionResult Result,int Id)>IssueAsync(string admin,string student,int course,CancellationToken ct=default){if(!await db.CourseEnrollments.AnyAsync(x=>x.StudentUserId==student&&x.CourseId==course&&x.Status==EnrollmentStatus.Approved,ct))return(CertificateActionResult.Forbidden,0);if(await db.CourseCertificates.AnyAsync(x=>x.StudentUserId==student&&x.CourseId==course,ct))return(CertificateActionResult.Duplicate,0);var seq=await db.CourseCertificates.CountAsync(ct)+1;var x=new CourseCertificate{StudentUserId=student,CourseId=course,IssuedByUserId=admin,IssueDate=DateOnly.FromDateTime(DateTime.Today),CertificateCode=$"TECH-CERT-{DateTime.UtcNow.Year}-{seq:0000}"};db.Add(x);await db.SaveChangesAsync(ct);return(CertificateActionResult.Success,x.Id);}
 public async Task<IReadOnlyList<CertificateDto>>GetStudentAsync(string s,CancellationToken ct=default)=>await Project(db.CourseCertificates.AsNoTracking().Where(x=>x.StudentUserId==s).OrderByDescending(x=>x.IssueDate)).ToListAsync(ct);
 public async Task<CertificateDto?>GetForUserAsync(string u,int id,bool admin,CancellationToken ct=default)=>await Project(db.CourseCertificates.AsNoTracking().Where(x=>x.Id==id&&(admin||x.StudentUserId==u))).FirstOrDefaultAsync(ct);
 private IQueryable<CertificateDto>Project(IQueryable<CourseCertificate>q)=>from x in q join student in db.Users.AsNoTracking() on x.StudentUserId equals student.Id join p in db.StudentProfiles.AsNoTracking() on student.Id equals p.UserId join issuer in db.Users.AsNoTracking() on x.IssuedByUserId equals issuer.Id select new CertificateDto(x.Id,x.CertificateCode,student.FullName,p.RegistrationNumber,x.Course.CourseCode,x.Course.Name,issuer.FullName,x.IssueDate);
}
