using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Badges;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Badges;
internal sealed class BadgeService(ApplicationDbContext db):IBadgeService
{
 public async Task<IReadOnlyList<BadgeDto>>GetAllAsync(CancellationToken ct=default)=>await db.Badges.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new BadgeDto(x.Id,x.Name,x.Description,x.IconPath,x.CreatedAtUtc)).ToListAsync(ct);
 public async Task<BadgeActionResult>CreateAsync(string n,string d,string? icon,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(n)||string.IsNullOrWhiteSpace(d))return BadgeActionResult.Invalid;if(await db.Badges.AnyAsync(x=>x.Name==n.Trim(),ct))return BadgeActionResult.Duplicate;db.Add(new Badge{Name=n.Trim(),Description=d.Trim(),IconPath=icon});await db.SaveChangesAsync(ct);return BadgeActionResult.Success;}
 public async Task<BadgeActionResult>DeleteAsync(int id,CancellationToken ct=default){var x=await db.Badges.FindAsync([id],ct);if(x is null)return BadgeActionResult.NotFound;db.Remove(x);await db.SaveChangesAsync(ct);return BadgeActionResult.Success;}
 public async Task<IReadOnlyList<AwardableStudentDto>>GetAwardableStudentsAsync(string f,CancellationToken ct=default)=>await(from e in db.CourseEnrollments.AsNoTracking() join u in db.Users.AsNoTracking() on e.StudentUserId equals u.Id join p in db.StudentProfiles.AsNoTracking() on u.Id equals p.UserId where e.Status==EnrollmentStatus.Approved&&db.FacultyCourses.Any(x=>x.FacultyUserId==f&&x.CourseId==e.CourseId) orderby u.FullName select new AwardableStudentDto(u.Id,u.FullName,p.RegistrationNumber,e.Course.CourseCode)).ToListAsync(ct);
 public async Task<BadgeActionResult>AwardAsync(string f,int badge,string student,CancellationToken ct=default){if(!await db.Badges.AnyAsync(x=>x.Id==badge,ct))return BadgeActionResult.NotFound;if(!await db.CourseEnrollments.AnyAsync(e=>e.StudentUserId==student&&e.Status==EnrollmentStatus.Approved&&db.FacultyCourses.Any(x=>x.FacultyUserId==f&&x.CourseId==e.CourseId),ct))return BadgeActionResult.Forbidden;if(await db.StudentBadges.AnyAsync(x=>x.BadgeId==badge&&x.StudentUserId==student,ct))return BadgeActionResult.Duplicate;db.Add(new StudentBadge{BadgeId=badge,StudentUserId=student,AwardedByUserId=f});await db.SaveChangesAsync(ct);return BadgeActionResult.Success;}
 public async Task<IReadOnlyList<StudentBadgeDto>>GetStudentBadgesAsync(string s,CancellationToken ct=default)=>await(from x in db.StudentBadges.AsNoTracking() join u in db.Users.AsNoTracking() on x.AwardedByUserId equals u.Id where x.StudentUserId==s orderby x.AwardedAtUtc descending select new StudentBadgeDto(x.Id,x.Badge.Name,x.Badge.Description,x.Badge.IconPath,u.FullName,x.AwardedAtUtc)).ToListAsync(ct);
}
