using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Enrollments;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Fees;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Enrollments;
internal sealed class EnrollmentService(ApplicationDbContext db):IEnrollmentService
{
 public async Task<IReadOnlyList<AvailableEnrollmentCourseDto>>GetAvailableCoursesAsync(string s,CancellationToken ct=default){var enrolled=db.CourseEnrollments.Where(x=>x.StudentUserId==s).Select(x=>x.CourseId);return await db.Courses.AsNoTracking().Where(x=>!enrolled.Contains(x.Id)).OrderBy(x=>x.CourseCode).Select(x=>new AvailableEnrollmentCourseDto(x.Id,x.CourseCode,x.Name,x.CreditHours,x.MonthlyFee)).ToListAsync(ct);}
 public async Task<IReadOnlyList<StudentEnrollmentRequestDto>>GetStudentEnrollmentsAsync(string s,CancellationToken ct=default)=>await db.CourseEnrollments.AsNoTracking().Where(x=>x.StudentUserId==s).OrderByDescending(x=>x.RequestedAtUtc).Select(x=>new StudentEnrollmentRequestDto(x.Id,x.CourseId,x.Course.CourseCode,x.Course.Name,x.Course.CreditHours,x.Course.MonthlyFee,x.Status,x.RequestedAtUtc,x.ReviewedAtUtc)).ToListAsync(ct);
 public async Task<EnrollmentActionResult>RequestAsync(string s,int c,CancellationToken ct=default){if(!await db.Courses.AnyAsync(x=>x.Id==c,ct))return EnrollmentActionResult.NotFound;if(await db.CourseEnrollments.AnyAsync(x=>x.StudentUserId==s&&x.CourseId==c,ct))return EnrollmentActionResult.Duplicate;db.Add(new CourseEnrollment{StudentUserId=s,CourseId=c,Status=EnrollmentStatus.Pending});await db.SaveChangesAsync(ct);return EnrollmentActionResult.Success;}
 public async Task<EnrollmentActionResult>ReviewAsync(int id,bool approve,CancellationToken ct=default){var e=await db.CourseEnrollments.Include(x=>x.Course).FirstOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return EnrollmentActionResult.NotFound;if(e.Status!=EnrollmentStatus.Pending)return EnrollmentActionResult.AlreadyReviewed;e.Status=approve?EnrollmentStatus.Approved:EnrollmentStatus.Rejected;e.ReviewedAtUtc=DateTime.UtcNow;if(approve)db.FeeRecords.Add(FeeService.CreateRecord(e,DateTime.Today.Month,DateTime.Today.Year));await db.SaveChangesAsync(ct);return EnrollmentActionResult.Success;}
}
