using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Challenges;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Challenges;
internal sealed class ChallengeService(ApplicationDbContext db):IChallengeService
{
 public async Task<IReadOnlyList<ChallengeDto>>GetFacultyChallengesAsync(string f,CancellationToken ct=default)=>await Project(db.CodingChallenges.AsNoTracking().Where(x=>x.FacultyUserId==f).OrderByDescending(x=>x.CreatedAtUtc)).ToListAsync(ct);
 public async Task<ChallengeActionResult>CreateAsync(string f,SaveChallengeRequest r,CancellationToken ct=default){if(r.CourseId<1||string.IsNullOrWhiteSpace(r.Title)||string.IsNullOrWhiteSpace(r.Description)||!Enum.IsDefined(r.Difficulty))return ChallengeActionResult.Invalid;if(!await db.FacultyCourses.AnyAsync(x=>x.FacultyUserId==f&&x.CourseId==r.CourseId,ct))return ChallengeActionResult.Forbidden;db.Add(new CodingChallenge{CourseId=r.CourseId,FacultyUserId=f,Title=r.Title.Trim(),Description=r.Description.Trim(),Difficulty=r.Difficulty,InputFormat=Clean(r.InputFormat),OutputFormat=Clean(r.OutputFormat),SampleInput=Clean(r.SampleInput),SampleOutput=Clean(r.SampleOutput),DueAtUtc=r.DueAtUtc});await db.SaveChangesAsync(ct);return ChallengeActionResult.Success;}
 public async Task<ChallengeActionResult>DeleteAsync(string f,int id,CancellationToken ct=default){var x=await db.CodingChallenges.FirstOrDefaultAsync(x=>x.Id==id&&x.FacultyUserId==f,ct);if(x is null)return ChallengeActionResult.NotFound;db.Remove(x);await db.SaveChangesAsync(ct);return ChallengeActionResult.Success;}
 public async Task<IReadOnlyList<CodingSubmissionDto>?>GetSubmissionsAsync(string f,int id,CancellationToken ct=default){if(!await db.CodingChallenges.AnyAsync(x=>x.Id==id&&x.FacultyUserId==f,ct))return null;return await SubmissionQuery(db.CodingSubmissions.AsNoTracking().Where(x=>x.ChallengeId==id).OrderByDescending(x=>x.SubmittedAtUtc)).ToListAsync(ct);}
 public async Task<IReadOnlyList<ChallengeDto>>GetStudentChallengesAsync(string s,CancellationToken ct=default){var ids=db.CourseEnrollments.Where(x=>x.StudentUserId==s&&x.Status==EnrollmentStatus.Approved).Select(x=>x.CourseId);return await Project(db.CodingChallenges.AsNoTracking().Where(x=>ids.Contains(x.CourseId)).OrderByDescending(x=>x.CreatedAtUtc)).ToListAsync(ct);}
 public async Task<ChallengeActionResult>SubmitAsync(string s,int id,string language,string code,CancellationToken ct=default){var x=await db.CodingChallenges.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return ChallengeActionResult.NotFound;if(x.DueAtUtc.HasValue&&DateTime.UtcNow>x.DueAtUtc)return ChallengeActionResult.Closed;if(!await db.CourseEnrollments.AnyAsync(e=>e.StudentUserId==s&&e.CourseId==x.CourseId&&e.Status==EnrollmentStatus.Approved,ct))return ChallengeActionResult.Forbidden;var allowed=new[]{"C#","JavaScript","Python","Java","C++","PHP"};if(!allowed.Contains(language)||string.IsNullOrWhiteSpace(code)||code.Length>30000)return ChallengeActionResult.Invalid;db.Add(new CodingSubmission{ChallengeId=id,StudentUserId=s,Language=language,SourceCode=code});await db.SaveChangesAsync(ct);return ChallengeActionResult.Success;}
 public async Task<IReadOnlyList<CodingSubmissionDto>>GetStudentSubmissionsAsync(string s,int id,CancellationToken ct=default)=>await SubmissionQuery(db.CodingSubmissions.AsNoTracking().Where(x=>x.ChallengeId==id&&x.StudentUserId==s).OrderByDescending(x=>x.SubmittedAtUtc)).ToListAsync(ct);
 private IQueryable<ChallengeDto>Project(IQueryable<CodingChallenge>q)=>q.Select(x=>new ChallengeDto(x.Id,x.Course.CourseCode,x.Course.Name,x.Title,x.Description,x.Difficulty,x.InputFormat,x.OutputFormat,x.SampleInput,x.SampleOutput,x.DueAtUtc,x.Submissions.Count));
 private IQueryable<CodingSubmissionDto>SubmissionQuery(IQueryable<CodingSubmission>q)=>from x in q join u in db.Users.AsNoTracking() on x.StudentUserId equals u.Id join p in db.StudentProfiles.AsNoTracking() on u.Id equals p.UserId select new CodingSubmissionDto(x.Id,u.FullName,p.RegistrationNumber,x.Language,x.SourceCode,x.SubmittedAtUtc);
 private static string?Clean(string?x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
}
