using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Notices;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Notices;
internal sealed class NoticeService(ApplicationDbContext db):INoticeService
{
 public async Task<IReadOnlyList<NoticeDto>> GetCreatedAsync(string creator,CancellationToken ct=default)=>await Project(db.Notices.AsNoTracking().Where(x=>x.CreatedByUserId==creator).OrderByDescending(x=>x.CreatedAtUtc)).ToListAsync(ct);
 public Task<NoticeActionResult> CreateAdminAsync(string id,SaveNoticeRequest r,CancellationToken ct=default)=>Create(id,r,false,ct);
 public Task<NoticeActionResult> CreateFacultyAsync(string id,SaveNoticeRequest r,CancellationToken ct=default)=>Create(id,r,true,ct);
 private async Task<NoticeActionResult>Create(string creator,SaveNoticeRequest r,bool faculty,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Title)||string.IsNullOrWhiteSpace(r.Message))return NoticeActionResult.Invalid;if(faculty){if(r.Audience!=NoticeAudience.Course||!r.CourseId.HasValue||!await db.FacultyCourses.AnyAsync(x=>x.FacultyUserId==creator&&x.CourseId==r.CourseId,ct))return NoticeActionResult.Forbidden;}else{if(r.Audience==NoticeAudience.Course&&(!r.CourseId.HasValue||!await db.Courses.AnyAsync(x=>x.Id==r.CourseId,ct)))return NoticeActionResult.Invalid;if(r.Audience==NoticeAudience.Student&&(string.IsNullOrWhiteSpace(r.StudentUserId)||!await db.StudentProfiles.AnyAsync(x=>x.UserId==r.StudentUserId,ct)))return NoticeActionResult.Invalid;}db.Add(new Notice{CreatedByUserId=creator,Title=r.Title.Trim(),Message=r.Message.Trim(),Audience=r.Audience,CourseId=r.Audience==NoticeAudience.Course?r.CourseId:null,StudentUserId=r.Audience==NoticeAudience.Student?r.StudentUserId:null,ImagePath=r.ImagePath});await db.SaveChangesAsync(ct);return NoticeActionResult.Success;}
 public async Task<NoticeActionResult>DeleteAsync(string creator,int id,CancellationToken ct=default){var x=await db.Notices.FirstOrDefaultAsync(x=>x.Id==id&&x.CreatedByUserId==creator,ct);if(x is null)return NoticeActionResult.NotFound;db.Remove(x);await db.SaveChangesAsync(ct);return NoticeActionResult.Success;}
 public async Task<IReadOnlyList<NoticeDto>>GetStudentNoticesAsync(string student,CancellationToken ct=default){var courseIds=db.CourseEnrollments.Where(x=>x.StudentUserId==student&&x.Status==EnrollmentStatus.Approved).Select(x=>x.CourseId);var q=db.Notices.AsNoTracking().Where(x=>x.Audience==NoticeAudience.AllStudents||(x.Audience==NoticeAudience.Student&&x.StudentUserId==student)||(x.Audience==NoticeAudience.Course&&x.CourseId.HasValue&&courseIds.Contains(x.CourseId.Value))).OrderByDescending(x=>x.CreatedAtUtc);return await Project(q).ToListAsync(ct);}
 private IQueryable<NoticeDto>Project(IQueryable<Notice>q)=>from x in q join creator in db.Users.AsNoTracking() on x.CreatedByUserId equals creator.Id join student in db.Users.AsNoTracking() on x.StudentUserId equals student.Id into students from student in students.DefaultIfEmpty() select new NoticeDto(x.Id,x.Title,x.Message,x.Audience,x.CourseId,x.Course==null?null:x.Course.CourseCode,x.StudentUserId,student==null?null:student.FullName,x.ImagePath,creator.FullName,x.CreatedAtUtc);
}
