using Microsoft.EntityFrameworkCore;using TechnifyERP.Application.Content;using TechnifyERP.Domain.Entities;using TechnifyERP.Domain.Enums;using TechnifyERP.Infrastructure.Persistence;
namespace TechnifyERP.Infrastructure.Content;
internal sealed class ContentService(ApplicationDbContext db):IContentService
{
 public async Task<IReadOnlyList<StudyMaterialDto>> GetFacultyMaterialsAsync(string f,CancellationToken ct=default)=>await Materials(MaterialQuery().Where(x=>x.FacultyUserId==f).OrderByDescending(x=>x.UploadedAtUtc)).ToListAsync(ct);
 public async Task<ContentActionResult> AddMaterialAsync(string f,SaveMaterialRequest r,CancellationToken ct=default){if(r.CourseId<1||string.IsNullOrWhiteSpace(r.Title)||string.IsNullOrWhiteSpace(r.FilePath))return ContentActionResult.Invalid;if(!await Assigned(f,r.CourseId,ct))return ContentActionResult.Forbidden;db.Add(new StudyMaterial{CourseId=r.CourseId,FacultyUserId=f,Title=r.Title.Trim(),Description=Clean(r.Description),FilePath=r.FilePath,OriginalFileName=r.OriginalFileName});await db.SaveChangesAsync(ct);return ContentActionResult.Success;}
 public async Task<ContentActionResult> DeleteMaterialAsync(string f,int id,CancellationToken ct=default){var x=await db.StudyMaterials.FirstOrDefaultAsync(x=>x.Id==id&&x.FacultyUserId==f,ct);if(x is null)return ContentActionResult.NotFound;db.Remove(x);await db.SaveChangesAsync(ct);return ContentActionResult.Success;}
 public async Task<IReadOnlyList<RecordedLectureDto>> GetFacultyLecturesAsync(string f,CancellationToken ct=default)=>await Lectures(LectureQuery().Where(x=>x.FacultyUserId==f).OrderByDescending(x=>x.CreatedAtUtc)).ToListAsync(ct);
 public async Task<ContentActionResult> AddLectureAsync(string f,SaveLectureRequest r,CancellationToken ct=default){if(r.CourseId<1||r.LectureNumber<1||string.IsNullOrWhiteSpace(r.Title)||!Uri.TryCreate(r.VideoUrl,UriKind.Absolute,out var uri)||uri.Scheme is not("http" or "https"))return ContentActionResult.Invalid;if(!await Assigned(f,r.CourseId,ct))return ContentActionResult.Forbidden;if(await db.RecordedLectures.AnyAsync(x=>x.CourseId==r.CourseId&&x.LectureNumber==r.LectureNumber,ct))return ContentActionResult.Duplicate;db.Add(new RecordedLecture{CourseId=r.CourseId,FacultyUserId=f,LectureNumber=r.LectureNumber,Title=r.Title.Trim(),Description=Clean(r.Description),VideoUrl=r.VideoUrl.Trim()});await db.SaveChangesAsync(ct);return ContentActionResult.Success;}
 public async Task<ContentActionResult> DeleteLectureAsync(string f,int id,CancellationToken ct=default){var x=await db.RecordedLectures.FirstOrDefaultAsync(x=>x.Id==id&&x.FacultyUserId==f,ct);if(x is null)return ContentActionResult.NotFound;db.Remove(x);await db.SaveChangesAsync(ct);return ContentActionResult.Success;}
 public async Task<IReadOnlyList<StudyMaterialDto>> GetStudentMaterialsAsync(string s,CancellationToken ct=default){var ids=ApprovedCourses(s);return await Materials(MaterialQuery().Where(x=>ids.Contains(x.CourseId)).OrderByDescending(x=>x.UploadedAtUtc)).ToListAsync(ct);}
 public async Task<IReadOnlyList<RecordedLectureDto>> GetStudentLecturesAsync(string s,CancellationToken ct=default){var ids=ApprovedCourses(s);return await Lectures(LectureQuery().Where(x=>ids.Contains(x.CourseId)).OrderBy(x=>x.Course.CourseCode).ThenBy(x=>x.LectureNumber)).ToListAsync(ct);}
 private IQueryable<int> ApprovedCourses(string s)=>db.CourseEnrollments.Where(x=>x.StudentUserId==s&&x.Status==EnrollmentStatus.Approved).Select(x=>x.CourseId);
 private Task<bool> Assigned(string f,int c,CancellationToken ct)=>db.FacultyCourses.AnyAsync(x=>x.FacultyUserId==f&&x.CourseId==c,ct);
 private IQueryable<StudyMaterial> MaterialQuery()=>db.StudyMaterials.AsNoTracking();private IQueryable<RecordedLecture> LectureQuery()=>db.RecordedLectures.AsNoTracking();private static string? Clean(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
 private IQueryable<StudyMaterialDto> Materials(IQueryable<StudyMaterial> q)=>from x in q join u in db.Users.AsNoTracking() on x.FacultyUserId equals u.Id select new StudyMaterialDto(x.Id,x.CourseId,x.Course.CourseCode,x.Course.Name,x.Title,x.Description,x.FilePath,x.OriginalFileName,u.FullName,x.UploadedAtUtc);
 private IQueryable<RecordedLectureDto> Lectures(IQueryable<RecordedLecture> q)=>from x in q join u in db.Users.AsNoTracking() on x.FacultyUserId equals u.Id select new RecordedLectureDto(x.Id,x.CourseId,x.Course.CourseCode,x.Course.Name,x.LectureNumber,x.Title,x.Description,x.VideoUrl,u.FullName,x.CreatedAtUtc);
}
