using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.Rendering;using TechnifyERP.Application.Assignments;using TechnifyERP.Application.Content;
namespace TechnifyERP.Areas.Faculty.Controllers;
[Area("Faculty"),Authorize(Roles="Faculty")]
public sealed class ContentController(IContentService content,IAssignmentService assignments,IWebHostEnvironment env):Controller
{
 public async Task<IActionResult>Index(CancellationToken ct){ViewBag.Materials=await content.GetFacultyMaterialsAsync(UserId,ct);ViewBag.Lectures=await content.GetFacultyLecturesAsync(UserId,ct);ViewBag.Courses=(await assignments.GetFacultyCoursesAsync(UserId,ct)).Select(x=>new SelectListItem($"{x.Code} — {x.Name}",x.Id.ToString()));return View();}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>AddMaterial(int courseId,string title,string? description,IFormFile? file,CancellationToken ct){if(file is null||file.Length<=0||file.Length>25*1024*1024){TempData["ErrorMessage"]="File required hai, maximum 25 MB.";return RedirectToAction(nameof(Index));}var ext=Path.GetExtension(file.FileName);var allowed=new[]{".pdf",".ppt",".pptx",".doc",".docx",".zip",".xls",".xlsx"};if(!allowed.Contains(ext,StringComparer.OrdinalIgnoreCase)){TempData["ErrorMessage"]="File type allowed nahi.";return RedirectToAction(nameof(Index));}var folder=Path.Combine(env.WebRootPath,"uploads","study-materials");Directory.CreateDirectory(folder);var name=$"{Guid.NewGuid():N}{ext.ToLowerInvariant()}";await using(var stream=System.IO.File.Create(Path.Combine(folder,name)))await file.CopyToAsync(stream,ct);var r=await content.AddMaterialAsync(UserId,new(courseId,title,description,$"/uploads/study-materials/{name}",Path.GetFileName(file.FileName)),ct);TempData[r==ContentActionResult.Success?"SuccessMessage":"ErrorMessage"]=r==ContentActionResult.Success?"Study material upload ho gaya.":"Material save nahi hua.";return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>DeleteMaterial(int id,CancellationToken ct){await content.DeleteMaterialAsync(UserId,id,ct);return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>AddLecture(int courseId,int lectureNumber,string title,string? description,string videoUrl,CancellationToken ct){var r=await content.AddLectureAsync(UserId,new(courseId,lectureNumber,title,description,videoUrl),ct);TempData[r==ContentActionResult.Success?"SuccessMessage":"ErrorMessage"]=r switch{ContentActionResult.Success=>"Recorded lecture add ho gaya.",ContentActionResult.Duplicate=>"Is course mein yeh lecture number pehle se hai.",_=>"Valid HTTP/HTTPS video URL aur fields check karein."};return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>DeleteLecture(int id,CancellationToken ct){await content.DeleteLectureAsync(UserId,id,ct);return RedirectToAction(nameof(Index));}
 private string UserId=>User.FindFirstValue(ClaimTypes.NameIdentifier)??throw new InvalidOperationException();
}
