using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.Rendering;using TechnifyERP.Application.Assignments;using TechnifyERP.Application.Notices;using TechnifyERP.Domain.Enums;
namespace TechnifyERP.Areas.Faculty.Controllers;
[Area("Faculty"),Authorize(Roles="Faculty")]
public sealed class NoticesController(INoticeService notices,IAssignmentService assignments,IWebHostEnvironment env):Controller
{
 public async Task<IActionResult>Index(CancellationToken ct){ViewBag.Notices=await notices.GetCreatedAsync(UserId,ct);ViewBag.Courses=(await assignments.GetFacultyCoursesAsync(UserId,ct)).Select(x=>new SelectListItem($"{x.Code} — {x.Name}",x.Id.ToString()));return View();}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Create(int courseId,string title,string message,IFormFile? image,CancellationToken ct){string?path=null;if(image is not null){var ext=Path.GetExtension(image.FileName);if(image.Length<=0||image.Length>5*1024*1024||!new[]{".jpg",".jpeg",".png",".webp"}.Contains(ext,StringComparer.OrdinalIgnoreCase)){TempData["ErrorMessage"]="Valid image max 5 MB upload karein.";return RedirectToAction(nameof(Index));}var folder=Path.Combine(env.WebRootPath,"uploads","notices");Directory.CreateDirectory(folder);var name=$"{Guid.NewGuid():N}{ext.ToLowerInvariant()}";await using var stream=System.IO.File.Create(Path.Combine(folder,name));await image.CopyToAsync(stream,ct);path=$"/uploads/notices/{name}";}var r=await notices.CreateFacultyAsync(UserId,new(title,message,NoticeAudience.Course,courseId,null,path),ct);TempData[r==NoticeActionResult.Success?"SuccessMessage":"ErrorMessage"]=r==NoticeActionResult.Success?"Course notice publish ho gaya.":"Notice save nahi hua.";return RedirectToAction(nameof(Index));}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Delete(int id,CancellationToken ct){await notices.DeleteAsync(UserId,id,ct);return RedirectToAction(nameof(Index));}private string UserId=>User.FindFirstValue(ClaimTypes.NameIdentifier)??throw new InvalidOperationException();
}
